name: update_oosc_surveys

# Run script everyday at 01:00 UTC
on:
  push:
    branches:    
      - 'main'
# Run script everyday at 01:00 UTC
  schedule: 
    - cron: '0 6 * * *' 
  
jobs:
  update_oosc_surveys:
    runs-on: ubuntu-latest
    env:
      KOBOTOOLBOX_URL: 'kf.kobotoolbox.org/'
      KOBOTOOLBOX_TOKEN: ${{ secrets.OOSC_KOBO_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Set up Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      - name: Update OOSC data
        run: |
          source("02_download_data_from_kobotoolbox.R")
        shell: Rscript {0}
      - name: commit
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add *
          git commit -m 'Update to oosc_surveys files'
